import 'package:common/utils/color_utils.dart';

import 'base_color.dart';
import 'tonal_palettes.dart';

class AppColors {
  static final BaseThemeColor appColorsDark = BaseThemeColor(
    shade: tonalPalettes.shade.tp900,
    textSecondary: tonalPalettes.neutral.tp400,
    textTertiary: tonalPalettes.neutral.tp200,
    surfaceDim: tonalPalettes.neutral.tp700,
    surface: tonalPalettes.neutral.tp500,
    surfaceBright: tonalPalettes.neutral.tp200,
    surfaceContainerLowest: tonalPalettes.neutral.tp800,
    surfaceContainerLow: tonalPalettes.neutral.tp600,
    surfaceContainer: tonalPalettes.neutral.tp400,
    surfaceContainerBright: tonalPalettes.neutral.tp300,
    surfaceContainerBrightest: tonalPalettes.neutral.tp100,
    onSurface: tonalPalettes.neutral.tp50,
    onSurfaceVariant: tonalPalettes.neutral.tp100,
    outline: tonalPalettes.neutral.tp400,
    outlineVariant: tonalPalettes.neutral.tp500,
    surfaceVariant: tonalPalettes.neutralVariant.tp0,
    shadowButton: tonalPalettes.tertiary.tp400,
    tonalPalettes: tonalPalettes,
    brightness: tonalPalettes.primary.tp70,
    primary: tonalPalettes.primary.tp600,
    onPrimary: tonalPalettes.primary.tp50,
    secondary: tonalPalettes.secondary.tp700,
    onSecondary: tonalPalettes.secondary.tp50,
    error: tonalPalettes.error.tp500,
    onError: tonalPalettes.error.tp50,
    background: tonalPalettes.neutralVariant.tp10,
    onBackground: tonalPalettes.primary.tp50,
    text: tonalPalettes.neutral.tp50,
    textLight: tonalPalettes.neutral.tp50,
    title: tonalPalettes.neutralVariant.tp95,
    description: tonalPalettes.neutralVariant.tp90,
    subTitle: tonalPalettes.neutralVariant.tp90,
    primaryContainer: tonalPalettes.primary.tp900,
    onPrimaryContainer: tonalPalettes.primary.tp200,
    secondaryContainer: tonalPalettes.secondary.tp900,
    onSecondaryContainer: tonalPalettes.secondary.tp400,
    tertiary: tonalPalettes.tertiary.tp700,
    onTertiary: tonalPalettes.tertiary.tp50,
    tertiaryContainer: tonalPalettes.tertiary.tp900,
    onTertiaryContainer: tonalPalettes.tertiary.tp200,
    errorContainer: tonalPalettes.error.tp300,
    onErrorContainer: tonalPalettes.error.tp900,
    shadow: tonalPalettes.neutralVariant.tp0,
    scrim: tonalPalettes.neutralVariant.tp0,
    inverseSurface: tonalPalettes.neutralVariant.tp0,
    onInverseSurface: tonalPalettes.neutralVariant.tp0,
    inversePrimary: tonalPalettes.neutralVariant.tp0,
    surfaceTin: tonalPalettes.neutralVariant.tp0,
    success: tonalPalettes.success.tp700,
    onSuccess: tonalPalettes.neutralVariant.tp0,
    successContainer: tonalPalettes.neutralVariant.tp0,
    onSuccessContainer: tonalPalettes.neutralVariant.tp0,
    gradientShine: tonalPalettes.shine.colorGradient,
    gradientBlueLight: tonalPalettes.blueLight.colorGradient,
    gradientNavy: tonalPalettes.navy.colorGradient,
    gradientOrangeFun: tonalPalettes.orangeFun.colorGradient,
    gradientSoda: tonalPalettes.soda.colorGradient,
    gradientVenice: tonalPalettes.venice.colorGradient,
    gradientLight: tonalPalettes.light.colorGradient,
    warning: tonalPalettes.warning.tp300,
    textDark: tonalPalettes.neutral.tp500,
  );

  static final BaseThemeColor appColorsLight = BaseThemeColor(
    shade: tonalPalettes.shade.tp0,
    surfaceContainer: tonalPalettes.neutral.tp400,
    textSecondary: tonalPalettes.neutral.tp300,
    textTertiary: tonalPalettes.neutral.tp200,
    surfaceDim: tonalPalettes.neutral.tp700,
    surface: tonalPalettes.neutral.tp500,
    surfaceBright: tonalPalettes.neutral.tp200,
    surfaceContainerLowest: tonalPalettes.neutral.tp800,
    surfaceContainerLow: tonalPalettes.neutral.tp600,
    surfaceContainerBright: tonalPalettes.neutral.tp300,
    surfaceContainerBrightest: tonalPalettes.neutral.tp100,
    onSurface: tonalPalettes.neutral.tp50,
    onSurfaceVariant: tonalPalettes.neutral.tp100,
    outline: tonalPalettes.neutral.tp400,
    outlineVariant: tonalPalettes.neutral.tp500,
    shadowButton: tonalPalettes.tertiary.tp400,
    tonalPalettes: tonalPalettes,
    brightness: tonalPalettes.primary.tp70,
    primary: tonalPalettes.primary.tp600,
    onPrimary: tonalPalettes.primary.tp50,
    secondary: tonalPalettes.secondary.tp700,
    onSecondary: tonalPalettes.secondary.tp50,
    error: tonalPalettes.error.tp500,
    onError: tonalPalettes.error.tp50,
    background: tonalPalettes.neutralVariant.tp10,
    onBackground: tonalPalettes.primary.tp50,
    text: tonalPalettes.neutral.tp600,
    textLight: tonalPalettes.neutral.tp50,
    title: tonalPalettes.neutralVariant.tp95,
    description: tonalPalettes.neutralVariant.tp90,
    subTitle: tonalPalettes.neutralVariant.tp90,
    primaryContainer: tonalPalettes.primary.tp900,
    onPrimaryContainer: tonalPalettes.primary.tp200,
    secondaryContainer: tonalPalettes.secondary.tp900,
    onSecondaryContainer: tonalPalettes.secondary.tp400,
    tertiary: tonalPalettes.tertiary.tp700,
    onTertiary: tonalPalettes.tertiary.tp50,
    tertiaryContainer: tonalPalettes.tertiary.tp900,
    onTertiaryContainer: tonalPalettes.tertiary.tp200,
    errorContainer: tonalPalettes.error.tp300,
    onErrorContainer: tonalPalettes.error.tp900,
    surfaceVariant: tonalPalettes.neutralVariant.tp0,
    shadow: tonalPalettes.neutralVariant.tp0,
    scrim: tonalPalettes.neutralVariant.tp0,
    inverseSurface: tonalPalettes.neutralVariant.tp0,
    onInverseSurface: tonalPalettes.neutralVariant.tp0,
    inversePrimary: tonalPalettes.neutralVariant.tp0,
    surfaceTin: tonalPalettes.neutralVariant.tp0,
    success: tonalPalettes.success.tp700,
    onSuccess: tonalPalettes.neutralVariant.tp0,
    successContainer: tonalPalettes.neutralVariant.tp0,
    onSuccessContainer: tonalPalettes.neutralVariant.tp0,
    gradientShine: tonalPalettes.shine.colorGradient,
    gradientBlueLight: tonalPalettes.blueLight.colorGradient,
    gradientNavy: tonalPalettes.navy.colorGradient,
    gradientOrangeFun: tonalPalettes.orangeFun.colorGradient,
    gradientSoda: tonalPalettes.soda.colorGradient,
    gradientVenice: tonalPalettes.venice.colorGradient,
    gradientLight: tonalPalettes.light.colorGradient,
    warning: tonalPalettes.warning.tp300,
    textDark: tonalPalettes.neutral.tp500,
  );
}

final tonalPalettes = TonalPalettes(
    primary: TonalPalettesColors(
      tp0: ColorUtils.parseHex('#E5F2FF'),
      tp10: ColorUtils.parseHex('#09132A'),
      tp20: ColorUtils.parseHex('#122654'),
      tp30: ColorUtils.parseHex('#1A397F'),
      tp40: ColorUtils.parseHex('#234CA9'),
      tp50: ColorUtils.parseHex('#E5F2FF'),
      tp60: ColorUtils.parseHex('#567FDC'),
      tp70: ColorUtils.parseHex('#809FE5'),
      tp80: ColorUtils.parseHex('#ABBFED'),
      tp90: ColorUtils.parseHex('#ABBFED'),
      tp95: ColorUtils.parseHex('#EAEFFB'),
      tp99: ColorUtils.parseHex('#FBFCFE'),
      tp100: ColorUtils.parseHex('#C2E0FF'),
      tp200: ColorUtils.parseHex('#9ECFFF'),
      tp300: ColorUtils.parseHex('#B2D9FF'),
      tp400: ColorUtils.parseHex('#4DA6FF'),
      tp500: ColorUtils.parseHex('#2491FF'),
      tp600: ColorUtils.parseHex('#0F77FF'),
      tp700: ColorUtils.parseHex('#0D65D9'),
      tp800: ColorUtils.parseHex('#0452B8'),
      tp900: ColorUtils.parseHex('#033F8F'),
    ),
    secondary: TonalPalettesColors(
      tp0: ColorUtils.parseHex('#000000'),
      tp10: ColorUtils.parseHex('#0F1624'),
      tp20: ColorUtils.parseHex('#233252'),
      tp30: ColorUtils.parseHex('#2E416B'),
      tp40: ColorUtils.parseHex('#3D578F'),
      tp50: ColorUtils.parseHex('#F2F6FF'),
      tp60: ColorUtils.parseHex('#708AC2'),
      tp70: ColorUtils.parseHex('#94A7D1'),
      tp80: ColorUtils.parseHex('#B8C4E0'),
      tp90: ColorUtils.parseHex('#DBE2F0'),
      tp95: ColorUtils.parseHex('#EDF0F7'),
      tp99: ColorUtils.parseHex('#FBFCFD'),
      tp100: ColorUtils.parseHex('#DBE7FF'),
      tp200: ColorUtils.parseHex('#C2D6FF'),
      tp300: ColorUtils.parseHex('#ADC9FF'),
      tp400: ColorUtils.parseHex('#99BBFF'),
      tp500: ColorUtils.parseHex('#80AAFF'),
      tp600: ColorUtils.parseHex('#5280FF'),
      tp700: ColorUtils.parseHex('#4570E5'),
      tp800: ColorUtils.parseHex('#2E4DA3'),
      tp900: ColorUtils.parseHex('#1F3161'),
    ),
    tertiary: TonalPalettesColors(
      tp0: ColorUtils.parseHex('#000000'),
      tp10: ColorUtils.parseHex('#2F1D04'),
      tp20: ColorUtils.parseHex('#5E3A08'),
      tp30: ColorUtils.parseHex('#8E580B'),
      tp40: ColorUtils.parseHex('#BD750F'),
      tp50: ColorUtils.parseHex('#F2FFFD'),
      tp60: ColorUtils.parseHex('#F0A842'),
      tp70: ColorUtils.parseHex('#F4BE71'),
      tp80: ColorUtils.parseHex('#F7D3A1'),
      tp90: ColorUtils.parseHex('#FBE9D0'),
      tp95: ColorUtils.parseHex('#FDF4E7'),
      tp99: ColorUtils.parseHex('#FFFDFA'),
      tp100: ColorUtils.parseHex('#DBFFF9'),
      tp200: ColorUtils.parseHex('#C2FFF5'),
      tp300: ColorUtils.parseHex('#80FFF2'),
      tp400: ColorUtils.parseHex('#47FFF3'),
      tp500: ColorUtils.parseHex('#00FFF0'),
      tp600: ColorUtils.parseHex('#4FDBDB'),
      tp700: ColorUtils.parseHex('#39C7CC'),
      tp800: ColorUtils.parseHex('#28AEB8'),
      tp900: ColorUtils.parseHex('#1C7F8A'),
    ),
    error: TonalPalettesColors(
      tp0: ColorUtils.parseHex('#000000'),
      tp10: ColorUtils.parseHex('#260D0F'),
      tp20: ColorUtils.parseHex('#4D191E'),
      tp30: ColorUtils.parseHex('#73262D'),
      tp40: ColorUtils.parseHex('#99333C'),
      tp50: ColorUtils.parseHex('#FFCCDD'),
      tp60: ColorUtils.parseHex('#CC666F'),
      tp70: ColorUtils.parseHex('#D98C93'),
      tp80: ColorUtils.parseHex('#E6B2B7'),
      tp90: ColorUtils.parseHex('#F2D9DB'),
      tp95: ColorUtils.parseHex('#F9ECED'),
      tp99: ColorUtils.parseHex('#FEFBFB'),
      tp100: ColorUtils.parseHex('#CAD0E5'),
      tp200: ColorUtils.parseHex('#CAD0E5'),
      tp300: ColorUtils.parseHex('#FF6699'),
      tp400: ColorUtils.parseHex('#CAD0E5'),
      tp500: ColorUtils.parseHex('#FF3377'),
      tp600: ColorUtils.parseHex('#CAD0E5'),
      tp700: ColorUtils.parseHex('#D6225E'),
      tp800: ColorUtils.parseHex('#CAD0E5'),
      tp900: ColorUtils.parseHex('#940635'),
    ),
    neutral: TonalPalettesColors(
      tp0: ColorUtils.parseHex('#000000'),
      tp10: ColorUtils.parseHex('#16181D'),
      tp20: ColorUtils.parseHex('#2C303A'),
      tp30: ColorUtils.parseHex('#424857'),
      tp40: ColorUtils.parseHex('#586074'),
      tp50: ColorUtils.parseHex('#F5F7FF'),
      tp60: ColorUtils.parseHex('#8B93A7'),
      tp70: ColorUtils.parseHex('#A8AEBD'),
      tp80: ColorUtils.parseHex('#C5C9D3'),
      tp90: ColorUtils.parseHex('#E2E4E9'),
      tp95: ColorUtils.parseHex('#F0F1F4'),
      tp99: ColorUtils.parseHex('#FCFCFD'),
      tp100: ColorUtils.parseHex('#EBEEFA'),
      tp200: ColorUtils.parseHex('#9FAACC'),
      tp300: ColorUtils.parseHex('#7987B2'),
      tp400: ColorUtils.parseHex('#596899'),
      tp500: ColorUtils.parseHex('#3D4D80'),
      tp600: ColorUtils.parseHex('#313D66'),
      tp700: ColorUtils.parseHex('#252E4D'),
      tp800: ColorUtils.parseHex('#181F33'),
      tp900: ColorUtils.parseHex('#0C0F1A'),
    ),
    neutralVariant: TonalPalettesColors(
      tp0: ColorUtils.parseHex('#FFFFFF'),
      tp10: ColorUtils.parseHex('#151B2C'),
      tp20: ColorUtils.parseHex('#212B45'),
      tp23: ColorUtils.parseHex('#26314F'),
      tp25: ColorUtils.parseHex('#293656'),
      tp28: ColorUtils.parseHex('#2E3C60'),
      tp30: ColorUtils.parseHex('#324067'),
      tp35: ColorUtils.parseHex('#3A4B78'),
      tp40: ColorUtils.parseHex('#42558A'),
      tp50: ColorUtils.parseHex('#5369AC'),
      tp60: ColorUtils.parseHex('#7588BD'),
      tp70: ColorUtils.parseHex('#97A6CE'),
      tp80: ColorUtils.parseHex('#BAC4DE'),
      tp90: ColorUtils.parseHex('#DCE1EF'),
      tp95: ColorUtils.parseHex('#EEF0F7'),
      tp99: ColorUtils.parseHex('#FCFCFD'),
      tp100: ColorUtils.parseHex('#F0F2F5'),
      tp200: ColorUtils.parseHex('#FFFFFF'),
      tp300: ColorUtils.parseHex('#FFFFFF'),
      tp400: ColorUtils.parseHex('#FFFFFF'),
      tp500: ColorUtils.parseHex('#FFFFFF'),
      tp600: ColorUtils.parseHex('#FFFFFF'),
      tp700: ColorUtils.parseHex('#FFFFFF'),
      tp800: ColorUtils.parseHex('#FFFFFF'),
      tp900: ColorUtils.parseHex('#FFFFFF'),
    ),
    success: TonalPalettesColors(
      tp0: ColorUtils.parseHex('#000000'),
      tp10: ColorUtils.parseHex('#0F2410'),
      tp20: ColorUtils.parseHex('#1F4720'),
      tp30: ColorUtils.parseHex('#2E6B31'),
      tp40: ColorUtils.parseHex('#3E8E41'),
      tp50: ColorUtils.parseHex('#E5FFF6'),
      tp60: ColorUtils.parseHex('#71C174'),
      tp70: ColorUtils.parseHex('#94D197'),
      tp80: ColorUtils.parseHex('#B8E0B9'),
      tp90: ColorUtils.parseHex('#DBF0DC'),
      tp95: ColorUtils.parseHex('#EDF7EE'),
      tp99: ColorUtils.parseHex('#FBFDFC'),
      tp100: ColorUtils.parseHex('#FFFFFF'),
      tp200: ColorUtils.parseHex('#FFFFFF'),
      tp400: ColorUtils.parseHex('#FFFFFF'),
      tp300: ColorUtils.parseHex('#AFFAE1'),
      tp500: ColorUtils.parseHex('#4BFAC0'),
      tp600: ColorUtils.parseHex('#FFFFFF'),
      tp700: ColorUtils.parseHex('#2EE5A8'),
      tp800: ColorUtils.parseHex('#FFFFFF'),
      tp900: ColorUtils.parseHex('#12B897'),
    ),
    warning: TonalPalettesColors(
      tp0: ColorUtils.parseHex('#000000'),
      tp10: ColorUtils.parseHex('#0F2410'),
      tp20: ColorUtils.parseHex('#1F4720'),
      tp30: ColorUtils.parseHex('#2E6B31'),
      tp40: ColorUtils.parseHex('#3E8E41'),
      tp50: ColorUtils.parseHex('#FFF5E5'),
      tp60: ColorUtils.parseHex('#71C174'),
      tp70: ColorUtils.parseHex('#94D197'),
      tp80: ColorUtils.parseHex('#B8E0B9'),
      tp90: ColorUtils.parseHex('#DBF0DC'),
      tp95: ColorUtils.parseHex('#EDF7EE'),
      tp99: ColorUtils.parseHex('#FBFDFC'),
      tp100: ColorUtils.parseHex('#FFFFFF'),
      tp200: ColorUtils.parseHex('#FFFFFF'),
      tp300: ColorUtils.parseHex('#FFCC80'),
      tp400: ColorUtils.parseHex('#234CA9'),
      tp500: ColorUtils.parseHex('#FF8D4D'),
      tp600: ColorUtils.parseHex('#FFFFFF'),
      tp700: ColorUtils.parseHex('#CC4B14'),
      tp800: ColorUtils.parseHex('#FFFFFF'),
      tp900: ColorUtils.parseHex('#66230A'),
    ),
    shade: TonalPalettesColors(
      tp0: ColorUtils.parseHex('#FFFFFF'),
      tp10: ColorUtils.parseHex('#0F2410'),
      tp20: ColorUtils.parseHex('#1F4720'),
      tp30: ColorUtils.parseHex('#2E6B31'),
      tp40: ColorUtils.parseHex('#3E8E41'),
      tp50: ColorUtils.parseHex('#FFF5E5'),
      tp60: ColorUtils.parseHex('#71C174'),
      tp70: ColorUtils.parseHex('#94D197'),
      tp80: ColorUtils.parseHex('#B8E0B9'),
      tp90: ColorUtils.parseHex('#DBF0DC'),
      tp95: ColorUtils.parseHex('#EDF7EE'),
      tp99: ColorUtils.parseHex('#FBFDFC'),
      tp100: ColorUtils.parseHex('#F0F2F5'),
      tp200: ColorUtils.parseHex('#E1E2E5'),
      tp300: ColorUtils.parseHex('#CDCED1'),
      tp400: ColorUtils.parseHex('#BEBFC2'),
      tp500: ColorUtils.parseHex('#AAABAD'),
      tp600: ColorUtils.parseHex('#828385'),
      tp700: ColorUtils.parseHex('#646566'),
      tp800: ColorUtils.parseHex('#464647'),
      tp900: ColorUtils.parseHex('#000000'),
    ),
    shine: TonalPalettesColorGradient(colorGradient: [
      ColorUtils.parseHex('#FFFFFF'),
      ColorUtils.parseHex('#A5D4FF')
    ]),
    venice: TonalPalettesColorGradient(colorGradient: [
      ColorUtils.parseHex('#AFDDFF'),
      ColorUtils.parseHex('#709DFF'),
      ColorUtils.parseHex('#5885FF'),
    ]),
    blueLight: TonalPalettesColorGradient(colorGradient: [
      ColorUtils.parseHex('#5DF5FF'),
      ColorUtils.parseHex('#55D0FF'),
      ColorUtils.parseHex('#4EAEFF'),
    ]),
    navy: TonalPalettesColorGradient(colorGradient: [
      ColorUtils.parseHex('#288CF5'),
      ColorUtils.parseHex('#2E54E5')
    ]),
    orangeFun: TonalPalettesColorGradient(colorGradient: [
      ColorUtils.parseHex('#FF965A'),
      ColorUtils.parseHex('#FC7749')
    ]),
    soda: TonalPalettesColorGradient(colorGradient: [
      ColorUtils.parseHex('#FFDB5A'),
      ColorUtils.parseHex('#FF9029')
    ]),
    light: TonalPalettesColorGradient(colorGradient: [
      ColorUtils.parseHex('#FFFFFF'),
      ColorUtils.parseHex('#F5F7FF')
    ]));
