# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Deploy a new version to the App Center"
  lane :publish_appcenter do |options|
    #TODO fastlane lane env 
    pathApk = "../build/app/outputs/apk/release/app-release.apk"
      puts "pathApk = " + pathApk
     
      appcenter_upload(
      api_token: "60225ecead478639e2249b65293b05e3ac610426",
      owner_name: "FSEL",
      app_name: "Planet-Defender",
      app_os: "Android",
      app_platform: "Java",
      apk: pathApk,
      release_notes:"#{options[:notes]}",
      notify_testers: true,
      should_clip: false,
      timeout: 600,
      )
      UI.message("#{lane_context[SharedValues::APPCENTER_DOWNLOAD_LINK]}")
    #   teams_url = "https://teams.microsoft.com/_#/conversations/19:aaf85d255d264c6f83e60680fa1b98b4@thread.v2?ctx=chat"
    #   teams_bot(
    #   teams_url: teams_url,
    #   title: "New Release Android app enable ",
    #   text: "Hi team !! this Link down load [Teams Bot]("+lane_context[SharedValues::APPCENTER_DOWNLOAD_LINK]+"). I can send messages on Microsoft Teams very easily from Fastlane.",
    #   activity_title: "Hey",
    #   activity_image: "https://seeklogo.com/images/F/fastlane-logo-6CA0B0B428-seeklogo.com.png"
    # )
  end
end
